# Generated by Django 5.2.7 on 2026-08-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
