# Generated by Django 5.2.7 on 2026-03-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_municipio_rank_nacional_00_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='decil24',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='populacao24',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='quintil24',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rc_24_pc',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='regiao',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='uf',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
