# Generated by Django 5.2.7 on 2026-08-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_indicadoresatuais_capag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadoresatuais',
            name='capag',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
