# Generated by Django 5.2.7 on 2026-06-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_municipio_decil24_alter_municipio_populacao24_and_more'),
        ('home', '0003_noticia_imagem_url'),
    ]

    operations = [
    ]
