# Generated by Django 5.2.7 on 2026-08-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_indicadoresatuais_capag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptaBrasil',
            fields=[
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dados_adapta_brasil', serialize=False, to='home.municipio')),
                ('bio_int_bio', models.FloatField(blank=True, null=True)),
                ('des_des_ter', models.FloatField(blank=True, null=True)),
                ('des_in_enx_ala', models.FloatField(blank=True, null=True)),
                ('rec_ris_est_hid', models.FloatField(blank=True, null=True)),
                ('sau_arb', models.FloatField(blank=True, null=True)),
                ('sau_lei_teg_ame', models.FloatField(blank=True, null=True)),
                ('sau_lei_vis', models.FloatField(blank=True, null=True)),
                ('sau_mal', models.FloatField(blank=True, null=True)),
                ('seg_ali_ace_con_ali', models.FloatField(blank=True, null=True)),
                ('seg_ali_dis', models.FloatField(blank=True, null=True)),
                ('seg_ene_ace', models.FloatField(blank=True, null=True)),
                ('seg_ene_dis', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
