# Generated by Django 5.2.7 on 2026-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_adaptabrasil'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptabrasil',
            name='media_ponderada',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
