# Generated by Django 5.2.7 on 2026-08-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_adaptabrasil_media_ponderada'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag_indicador_I',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag_indicador_II',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag_indicador_III',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
