# Generated by Django 5.2.7 on 2026-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_indicadoresatuais_capag_indicador_i_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag_qualidade_fiscal',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
