# Generated by Django 5.2.7 on 2026-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_indicadoresatuais_capag_qualidade_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome único do consórcio, como aparece no filtro', max_length=255, unique=True)),
                ('municipios', models.ManyToManyField(blank=True, help_text='Municípios que compõem o consórcio', related_name='consorcios', to='home.municipio')),
            ],
            options={
                'verbose_name': 'Consórcio',
                'verbose_name_plural': 'Consórcios',
                'ordering': ['nome'],
            },
        ),
    ]
