# Generated by Django 5.2.7 on 2026-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_consorcio'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag_indicador_III_nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag_indicador_II_nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadoresatuais',
            name='capag_indicador_I_nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
