# Generated by Django 5.2.7 on 2026-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_indicadoresatuais_capag_indicador_iii_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresatuais',
            name='rgf_comprometimento_pessoal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadoresatuais',
            name='rgf_divida_consolidada_liquida',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
