# Generated by Django 5.2.7 on 2026-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_indicadoresatuais_rgf_comprometimento_pessoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadoresatuais',
            name='indicador_equilibrio_fiscal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
