"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, ".env"))

MAPBOX_PUBLIC_TOKEN = os.getenv("MAPBOX_PUBLIC_TOKEN", "")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "A variável de ambiente DJANGO_SECRET_KEY não está definida. "
        "Configure-a no arquivo .env (desenvolvimento) ou nas variáveis de ambiente (produção)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 't')

# Lê a variável ou usa fallbacks - Aceita múltiplos hosts separados por vírgula
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "ifem.onrender.com,localhost,127.0.0.1").split(",")

# Adicione também esta configuração para evitar erros de CSRF em formulários
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "https://subfinanciados-ifem.onrender.com,https://*.onrender.com").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'home',
    'ifem',
    'map',
    'detail_mun',
    'detail_agg',
     
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Comprime respostas dinâmicas (HTML/JSON). Crítico para a API de GeoJSON do mapa,
    # que trafega ~2.8MB sem compressão. Seguro aqui: respostas são dados públicos (sem risco BREACH).
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base_templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'map.context_processors.public_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuração de banco de dados híbrida
# Prioriza a DATABASE_URL (Supabase/Prod) e mantém SQLite como fallback
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{os.path.join(BASE_DIR, "db.sqlite3")}',
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Se NÃO for DEBUG (produção), DATABASE_URL é OBRIGATÓRIA
if not DEBUG:
    _db_url = os.getenv("DATABASE_URL", "")
    if not _db_url or _db_url.startswith("sqlite"):
        raise RuntimeError(
            "ERRO CRÍTICO: DATABASE_URL não configurada em produção! "
            "Configure a variável de ambiente no painel do Render."
        )

# Se for PostgreSQL, força SSL
if os.getenv("DATABASE_URL") and not os.getenv("DATABASE_URL").startswith("sqlite"):
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['sslmode'] = 'require'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

USE_I18N = True
USE_L10N = True

# Define o idioma padrão
LANGUAGE_CODE = 'pt-br'

# Define o fuso horário
TIME_ZONE = 'America/Sao_Paulo'

# Opcional, para garantir que a formatação do Brasil seja usada para números
USE_THOUSAND_SEPARATOR = True 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'base_statics',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuração de Armazenamento (Obrigatório no Django 5+)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# SECURITY SETTINGS
# ==========================================
# Redireciona HTTP para HTTPS - Ativado apenas em produção via Variável de Ambiente
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 't')

# Atrás do Nginx (que termina o TLS), a requisição chega ao Gunicorn como HTTP interno.
# O proxy seta `X-Forwarded-Proto` (proxy_set_header ... $scheme, sobrescrevendo o valor do
# cliente), e este header diz ao Django que a conexão externa é HTTPS. Sem isso,
# SECURE_SSL_REDIRECT=True entra em loop infinito: o app nunca "enxerga" o https e redireciona
# de novo. Seguro em dev (o header não vem, nada muda) e em prod (só o Nginx local, em
# 127.0.0.1, fala com o container — o cliente não consegue forjar o header).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG and SECURE_SSL_REDIRECT:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Garante que em desenvolvimento ou se SSL_REDIRECT for False, esses valores sejam limpos
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0

# Headers contra exploits web e Sniffing (Seguros para manter ativos)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
